[config]
skip_core_tasks = true

[env]
TARGET = "x86_64-unknown-linux-gnu"
PROFILE = "dev"
CHANNEL = "1.84.0"

[env.arm_dev]
TARGET = "armv7-unknown-linux-gnueabi"
PROFILE = "dev"
CHANNEL = "1.84.0"

[env.arm_release]
TARGET = "armv7-unknown-linux-gnueabi"
PROFILE = "release"
CHANNEL = "1.84.0"

[env.aarch64_dev]
TARGET = "aarch64-unknown-linux-gnu"
PROFILE = "dev"
CHANNEL = "1.84.0"

[env.aarch64_release]
TARGET = "aarch64-unknown-linux-gnu"
PROFILE = "release"
CHANNEL = "1.84.0"

[env.x64_dev]
TARGET = "x86_64-unknown-linux-gnu"
PROFILE = "dev"
CHANNEL = "1.84.0"

[env.x64_release]
TARGET = "x86_64-unknown-linux-gnu"
PROFILE = "release"
CHANNEL = "1.84.0"

[env.i686_dev]
TARGET = "i686-unknown-linux-gnu"
PROFILE = "dev"
CHANNEL = "1.84.0"

[env.i686_release]
TARGET = "i686-unknown-linux-gnu"
PROFILE = "release"
CHANNEL = "1.84.0"

[env.powerpc_dev]
TARGET = "powerpc-unknown-linux-gnu"
PROFILE = "dev"
CHANNEL = "nightly"

[env.powerpc_release]
TARGET = "powerpc-unknown-linux-gnu"
PROFILE = "release"
CHANNEL = "nightly"

[tasks.default]
alias = "compile"

[tasks.compile]
toolchain = "${CHANNEL}"
command = "cargo"
args = [
  "build",
  "--profile", "${PROFILE}",
  "--target", "${TARGET}",
]

[tasks.test]
toolchain = "${CHANNEL}"
command = "cargo"
args = [
  "test",
  "--target", "${TARGET}",
  "--",
  "--nocapture",
  "--test-threads=1"
]

[tasks.test-platform]
command = "cargo"
args = [
  "make",
  "-p", "${PLATFORM}_dev",
  "test"
]
env = { PLATFORM = "x64" }

[tasks.test-arm]
extend = "test-platform"
env = { PLATFORM = "arm" }

[tasks.test-aarch64]
extend = "test-platform"
env = { PLATFORM = "aarch64" }

[tasks.test-i686]
extend = "test-platform"
env = { PLATFORM = "i686" }

[tasks.test-x64]
extend = "test-platform"
env = { PLATFORM = "x64" }

[tasks.test-powerpc]
extend = "test-platform"
env = { PLATFORM = "powerpc" }

[tasks.test-all]
dependencies = [
  "test-arm",
  "test-aarch64",
  "test-i686",
  "test-x64",
  "test-powerpc",
]

[tasks.fuzz-guest-shadow-debug]

[tasks.fuzz-guest-shadow-release]

[tasks.fuzz-guest-tracking-debug]

[tasks.fuzz-guest-tracking-release]

[tasks.fuzz-default-frontend-debug]

[tasks.fuzz-default-frontend-release]
