[config]
skip_core_tasks = true

[env]
TARGET = "x86_64-unknown-linux-gnu"
JOBS = "8"

[tasks.default]
alias = "test"

[tasks.test]

[tasks.test-all]

[tasks.fuzz_guest_shadow_debug]
toolchain = "nightly"
command = "cargo"
args = [
  "fuzz",
  "run",
  "--sanitizer", "none",
  "--target", "${TARGET}",
  "guest_shadow",
]

[tasks.fuzz_guest_shadow_release]
toolchain = "nightly"
command = "cargo"
args = [
  "fuzz",
  "run",
  "--sanitizer", "none",
  "--target", "${TARGET}",
  "--release",
  "guest_shadow",
  "--",
  "-jobs=${JOBS}",
]


[tasks.fuzz_guest_tracking_debug]
toolchain = "nightly"
command = "cargo"
args = [
  "fuzz",
  "run",
  "--sanitizer", "none",
  "--target", "${TARGET}",
  "guest_tracking",
]

[tasks.fuzz_guest_tracking_release]
toolchain = "nightly"
command = "cargo"
args = [
  "fuzz",
  "run",
  "--sanitizer", "none",
  "--target", "${TARGET}",
  "--release",
  "guest_tracking",
  "--",
  "-jobs=${JOBS}",
]

