import "../just/env.just"

[unix]
compile_runner:
  #!/bin/bash
  source {{ DOTENV }}
  cargo \
    +${CHANNEL} \
    build \
    --package runner \
    --target x86_64-unknown-linux-gnu \
    --profile {{ PROFILE }} \
    --target-dir {{ TARGET_DIR }} \
    --features ${QEMU_ARCH}

[unix]
fix_runner:
  #!/bin/bash
  source {{ DOTENV }}
  cargo \
    +${CHANNEL} \
    fix \
    --package runner \
    --target x86_64-unknown-linux-gnu \
    --profile {{ PROFILE }} \
    --target-dir {{ TARGET_DIR }} \
    --features ${QEMU_ARCH} \
    --allow-dirty

[unix]
build_runner: compile_runner
